repos:

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v2.4.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        name: isort (python)
        args: [
          '--line-length=120',
          '--multi-line=3',
        ]

-   repo: https://github.com/psf/black
    rev: '23.11.0'
    hooks:
      - id: black
        args: [--line-length=120]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.0'
    hooks:
    -   id: mypy
        additional_dependencies: [tokenize-rt==5.2.0, pandas-stubs==2.1.1.230928, types-click==7.1.8]
        args: [--strict, --ignore-missing-imports]

-   repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
